<!DOCTYPE html>
<html lang="en">

<head>
    <title>suivi amana à l'international</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="shortcut icon" href="favicon_3.ico" type="image/x-icon">
    <link rel="icon" href="favicon_3.ico" type="image/x-icon">
</head>

<body>
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header"></div>
            <a class="navbar-brand pull-right navbar-rightt" href="index.php">
                <img src="img/logo.png" alt="Amana" />
            </a>
        </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div id="main" class="col-md-7">
